language: python

cache: pip

matrix:
  include:
  - python: 2.7
  - python: 3.4
  - python: 3.5
  - python: 3.6

install:
- travis_retry pip install --upgrade pip
- travis_retry pip install --upgrade setuptools wheel
- travis_retry pip install --upgrade tox-travis

script:
- tox
