language: python
cache: pip
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
install:
  - travis_retry pip install --upgrade pip
  - travis_retry pip install --upgrade setuptools wheel
  - travis_retry pip install --upgrade coveralls tox-travis
script:
  - tox
after_success:
  - coveralls --rcfile=.coveragerc --verbose
