language: python
cache: pip
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install:
  - travis_retry pip install --upgrade pip
  - travis_retry pip install --upgrade setuptools wheel coveralls
script:
  - |
    if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]] || [[ $TRAVIS_PYTHON_VERSION == '3.3' ]] || [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then
        travis_retry pip install tox
        tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
    else
        travis_retry pip install tox-travis
        tox
    fi
after_success:
  - coveralls --rcfile=.coveragerc --verbose
