language: python
cache: pip
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install:
  - travis_retry pip install tox-travis coveralls
script:
  - tox
after_success:
  - coveralls --rcfile=.coveragerc --verbose
